name: test and lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.4'] # TODO test against 3.3, 3.4 too

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run bundle
      run: bundle 
    - name: Set up yardocs
      run: bundle exec yard gems
    - name: Run tests
      run: bundle exec rspec
    - name: Run rubocop
      run: bundle exec rubocop
